#!/bin/bash
echo "Please Enter a number or 0 To exit : " | tr "\n" " "
read value
if [ $value -lt 0 ]
then 
      echo "please enter positive number "
      read value
else 
      continue
fi       
sum=0
number=0
average=0
while [  $value != 0 ]; 
do              
            
	sum=`expr $value + $sum`
	number=`expr $number + 1`
	echo "Please Enter a number or 0 To exit :" | tr "\n" " " 
	read value
if [ $value -lt 0 ]
then 
      echo "please enter positive number "
      read value
else 
      continue
fi       
done

average=`expr $sum / $number` 

echo "The average of values is : $average "
